// Auth
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Pipeline
export const FETCH_PROJECTS_INIT = "FETCH_PROJECTS_INIT";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const CLEAR_CURRENT_PROJECT = "CLEAR_CURRENT_PROJECT";
